name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy-frontend:
    name: Build Frontend and Push to Build Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Frontend Dependencies
        run: npm ci

      - name: Build Frontend
        run: npm run build

      - name: Deploy to Build Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: build
          force_orphan: true

  deploy-firebase:
    name: Deploy Functions and Firestore
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Functions Dependencies
        working-directory: ./functions
        run: npm ci

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy Firebase Functions and Firestore
        run: firebase deploy --only functions,firestore --project newscards-6564e
